org: pdechery
app: aws-serverless-project
service: simple-lambda-app
frameworkVersion: "3"

provider:
  name: aws
  profile: default
  stage: dev
  runtime: python3.11

functions:
  send_message_sqs:
    handler: send_message_sqs.handler
    events:
      - httpApi:
          method: get
          path: /send
    environment:
        QUEUE_URL: !Ref ArtistsQueue
  send_records_dynamo:
    handler: send_records_dynamo.handler
    timeout: 10 # seconds
    events:
      - sqs:
          arn: !GetAtt ArtistsQueue.Arn
          batchSize: 5

# CloudFormation Syntax
resources:
  Resources:
    ArtistsDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: artists
        KeySchema:
          - AttributeName: artist
            KeyType: HASH
          - AttributeName: song
            KeyType: RANGE
        AttributeDefinitions:
          - AttributeName: artist
            AttributeType: S
          - AttributeName: song
            AttributeType: S
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    ArtistsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub '${AWS::StackName}-artists-queue'
        # 6 times the lambda function's timeout
        VisibilityTimeout: 60
        # Messages will be stored (and retried) up to 2 days
        MessageRetentionPeriod: 172800
        RedrivePolicy:
          # Jobs will be retried 5 times
          maxReceiveCount: 1
          # Send failed messages to the dead letter queue
          deadLetterTargetArn: !GetAtt ArtistsDLQ.Arn
    ArtistsDLQ:
      Type: AWS::SQS::Queue
      Properties:
        # Store messages up to 14 days (the max)
        MessageRetentionPeriod: 1209600


plugins:
  - serverless-python-requirements
package:
  patterns:
    - "!.git/**"
    - "!node_modules/**"
    - "!venv/**"
    - "!data/**"
